### ISSUE TITLE
Monitored Resource going in anomaly state inspite of running remediation action repeatedly

### ISSUE THREAD

**Issue by sidrocks** [Infosys/Intelligent-Bot-Management-#1]
It is observed that a resource is repeatedly going in an anomaly state after running the remediation action. Inspite of repeated failures during consecutive monitoring checks and remediation actions for the same resource the system is running in an endless loop of trying to heal the resource resulting in wasteful utilisation of system resources. In such a situation the system should deactivate such a resource from future monitoring or remediation actions as it may require some manual intervention to get the issue resolved.

**Comment by SudhaAmsoleInfy** [comment]
This issue will be addressed in upcomming release.

**Comment by SudhaAmsoleInfy** [comment]
We have introduced threashold parameters to control the repeated failures while monitoring, remediating and/or detecting anomaly. System will retry the monitoring/remediation in case of continuous failure's till the thresold limit, if not resolved in the retry attempts, the resource will be deactivated and a notification will be sent to investigate the issue manually. once the issue is fixed, resource can be activated for monitoring again.

**Comment by sidrocks** [comment]
Ok Thanks for the update
